adjective1 = input("Enter an adjective ") 
nationality = input("Enter a Nationality ") 
person = input("Enter a name ")
noun1 = input("Enter a noun ") 
adjective2 = input("Enter an adjective ") 
noun2 = input("Enter a noun ") 
adjective3 = input("Enter an adjective ") 
adjective4 = input("Enter an adjective ")
plural_noun = input("Enter a plural noun ") 
noun3 = input("Enter a noun ")
number1 = input("Enter any number ")
food1 = input("Enter the name of any food item ") 
food2 = input("Enter the name of any food item ") 
number2 = input("Enter any number ")
print (" Pizza was invented by a " + adjective1 + " - " + nationality + " chef named "+ person)
print(" To make a pizza, you need to take a lump of " + noun1 + " and make a thin, round " + adjective2 + " " + noun2)
print(" Then you cover it with " + adjective3 + " sauce, " + adjective4 + " cheese, and fresh chopped " + plural_noun)
print(" Next you have to bake it in a very hot " + noun3 + ". When it is done, cut it into " + number1 + " shapes.")
print(" Some like " + food1 + " pizza the best, but my favorite is the " + food2 + " pizza.")
print(" If I could, I would eat pizza " + number2 + " times a day!")
